### ISSUE TITLE
Any difference between electron-store?

### ISSUE THREAD

**Issue by kawpii** [reZach/secure-electron-store#4]
I do not see your claims about `fs` usage still exists in electron store.

**Comment by reZach** [comment]
Thanks for your investigation @kaushalyap. As you see [on this line](https://github.com/sindresorhus/electron-store/blob/master/index.js#L4), [`electron-store`](https://github.com/sindresorhus/electron-store) loads up the [conf](https://github.com/sindresorhus/conf) library which [loads the `fs` library](https://github.com/sindresorhus/conf/blob/master/source/index.ts#L1).

Because the electron-store is meant to be used in your renderer processes directly, which is why they [recommend you need to enable the remote module](https://github.com/sindresorhus/electron-store#when-on-electron-10-or-later-you-need-to-enable-the-enableremotemodule-option-to-be-able-to-use-it-directly-in-the-renderer-process), using electron-store can be less secure because a best-practice of security is [not using the remote module](https://www.electronjs.org/docs/tutorial/security#15-disable-the-remote-module).

I hope this explanation helps a bit!

**Comment by kawpii** [comment]
thanks for the explanation, did not knew about conf using fs.
